const mainProjects = [
	{
		id: 1,
		title: "Portfolio Website",
		description: "Personal Portfolio Website. You're Here Only!",
		techs: "HTML, CSS, Javascript",
		image: "portfolio.jpg",
		linkView: "http://www.nguyenthanhdung.tk/",
		linkSourceCode: "https://github.com/dung812/portfolio.git",
	},
	{
		id: 2,
		title: "Ecommerce ASP.NET-MVC Online shopping men clothes",
		description: "E-commerce website Based On ASP.NET MVC 5 And SQL-Server Database.",
		techs: "ASP.NET MVC, Entity Framework, LINQ to SQL, SQL Server",
		image: "ecommerce.jpg",
		linkView: "https://youtu.be/xcqi7A-sCgo",
		linkSourceCode: "https://github.com/dung812/E-commerce_ASPNET.git",
	},
	{
		id: 3,
		title: "Ecommerce Online shopping clothes",
		description: "E-commerce website using WooCommerce a plugin of WordPress.",
		techs: "WordPress",
		image: "woocommerce.jpg",
		linkView: "http://onlineshopdemo.unaux.com/",
		linkSourceCode: "http://onlineshopdemo.unaux.com/",
	},
	{
		id: 4,
		title: "Manage Assets",
		description: "The Project is an assignment I developed during the time I trained at NashTech company. The project uses the Scrum process and deployed in Azure DevOps.",
		techs: "ASP.NET Core, Identity Server 4, ReactJS, Redux toolkit, Redux Thunk, Scrum Process, Azure Devops",
		image: "manage-asset.png",
		linkView: "https://github.com/dung812/Manage-Assets-RookieProgram",
		linkSourceCode: "https://github.com/dung812/Manage-Assets-RookieProgram",
	},
	{
		id: 5,
		title: "E-commerce Shoes Shopping",
		description: "The E-commerce Project is my thesis. The project divide 2 site is customer site and admin site, customer site is using MVC model and Admin site using SPA + Web API.",
		techs: "ASP.NET Core, bootstrap, Javascript, Ajax/jQuery, ReactJS, Redux toolkit, Redux middleware thunk, Axios, JWT",
		image: "ShoesShop.png",
		linkView: "http://ntdung812-001-site1.btempurl.com/",
		linkSourceCode: "https://github.com/dung812/Assignment-Ecommerce-Rookie.git",
	},
]

const cloneProjects = [
	{
		id: 1,
		title: "Clone furniture website",
		description: "A static web page I completed in sophomore",
		techs: "HTML, CSS, Javascript, Bootstrap 4",
		image: "furniture.jpg",
		linkView: "https://dung812.github.io/furniture_clone/",
		linkSourceCode: "https://github.com/dung812/furniture_clone.git",
	},
	{
		id: 2,
		title: "Clone the-band w3c website",
		description: "The last project of course HTML, CSS in fullstack.edu.vn",
		techs: "HTML, CSS",
		image: "theband.jpg",
		linkView: "https://dung812.github.io/the-band_clone/",
		linkSourceCode: "https://github.com/dung812/the-band_clone.git",
	},
	{
		id: 3,
		title: "Landing page - Freelancer job",
		description: "Build a static website for customer design requirement",
		techs: "HTML, CSS, Javascript",
		image: "freelancer-landingpage-ntpm.jpg",
		linkView: "https://dung812.github.io/freelancer-landingpage/",
		linkSourceCode: "https://github.com/dung812/freelancer-landingpage.git",
	},	
	{
		id: 4,
		title: "Lucky draw web app - Freelancer job",
		description: "Build a lucky draw web app for customers after finishing order, display a random gift after the customer chooses one of the gift boxes.",
		techs: "HTML, CSS/SCSS, Javascript",
		image: "freelancer-luckyDraw-ninjavan.jpg",
		linkView: "https://dung812.github.io/task-1-intern/",
		linkSourceCode: "https://github.com/dung812/task-1-intern.git",
	},
]

const miniProjects = [
	{
		id: 1,
		title: "Quiz Web App",
		description: "Simple quiz application",
		techs: "HTML, CSS, TailwindCSS, Javascript",
		image: "quiz.jpg",
		linkView: "https://dung812.github.io/quiz_simpleJS/",
		linkSourceCode: "https://github.com/dung812/quiz_simpleJS.git",
	},
	{
		id: 2,
		title: "Memory game",
		description: "Simple memory game",
		techs: "HTML, CSS, SCSS, Javascript",
		image: "memory-game.jpg",
		linkView: "https://dung812.github.io/memory-game_simpleJS/",
		linkSourceCode: "https://github.com/dung812/memory-game_simpleJS.git",
	},
	{
		id: 3,
		title: "To-do list website",
		description: "Add your task onto to-do list. Stores in LocalStorage",
		techs: "HTML, CSS, Javascript",
		image: "todolist.jpg",
		linkView: "https://dung812.github.io/todolist/",
		linkSourceCode: "https://github.com/dung812/todolist.git",
	},
	{
		id: 4,
		title: "Simple slider",
		description: "Simple slider website, zooming when hover into images",
		techs: "HTML, CSS, SCSS, Javascript",
		image: "simple-slider.jpg",
		linkView: "https://dung812.github.io/simple-slider_simpleJS/",
		linkSourceCode: "https://github.com/dung812/simple-slider_simpleJS.git",
	},
	{
		id: 5,
		title: "Password generator",
		description: "A basic password generator as per the user-selected criteria",
		techs: "HTML, CSS, Javascript",
		image: "render-password.jpg",
		linkView: "https://dung812.github.io/render-password_simpleJS/",
		linkSourceCode: "https://github.com/dung812/render-password_simpleJS.git",
	},
	{
		id: 6,
		title: "Check strength of password",
		description: "Check how strong and secure is your password",
		techs: "HTML, CSS, Javascript",
		image: "strength-password.jpg",
		linkView: "https://dung812.github.io/strength-password_simpleJS/",
		linkSourceCode: "https://github.com/dung812/strength-password_simpleJS.git",
	},
	{
		id: 7,
		title: "Create CV",
		description: "A simple form to create quickly your CV",
		techs: "HTML, CSS, Javascript",
		image: "create-cv.jpg",
		linkView: "https://dung812.github.io/create-cv_simpleJS/",
		linkSourceCode: "https://github.com/dung812/create-cv_simpleJS.git",
	},
	{
		id: 8,
		title: "Simple stopwatch",
		description: "Simple stopwatch with start, stop and reset features",
		techs: "HTML, CSS, Javascript",
		image: "stopwatch.jpg",
		linkView: "https://dung812.github.io/stopwatch_simpleJS/",
		linkSourceCode: "https://github.com/dung812/stopwatch_simpleJS.git",
	},
	{
		id: 9,
		title: "Countdown",
		description: "A countdown timer to the end date of the course promotion",
		techs: "HTML, CSS, Javascript",
		image: "giveaway.jpg",
		linkView: "https://dung812.github.io/giveaway-countdown_simpleJS/",
		linkSourceCode: "https://github.com/dung812/giveaway-countdown_simpleJS.git",
	},
]

const apiProjects = [
	{
		id: 1,
		title: "Manager Blog",
		description: "It's a simple web page that fetch a Fake REST API of JSON Server and the database was deployed on Heroku. Feature to Create, Read, Update, Delete, Filter blog list",
		techs: "HTML, CSS, JavaScript, JSON Server",
		image: "blog.jpg",
		linkView: "https://dung812.github.io/JSON-Server-CRUDblog_API/",
		linkSourceCode: "https://github.com/dung812/JSON-Server-CRUDblog_API.git",
	},
	{
		id: 3,
		title: "Clone sales websites",
		description: "Simple SPA website with Angular, this website has some functions like dynamic website such as view product detail, shopping cart using localstorage, CRUD dashboard API, Order manager,...",
		techs: "HTML, SCSS, TailwindCSS, Angular",
		image: "ssstutter-clone.jpg",
		linkView: "https://clothesworld.netlify.app/",
		linkSourceCode: "https://github.com/dung812/clothes-clone_Angular.git",
	},
]